import type { Metadata } from "next"
import { ThemeProvider } from "@/shared/components/theme-provider"
import { ModeToggle } from "@/shared/components/ModeToggle"
import { Inter } from "next/font/google"
import "./globals.css"
import Head from "next/head"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-dvh w-dvw box-border" suppressHydrationWarning>
      <Head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4380050393572271"
          crossOrigin="anonymous"></script>
      </Head>
      <body className="h-full w-full  bg-background ">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModeToggle className="absolute top-4 right-4 z-10" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
